remote: true
hybrid: true
onsite: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false  # Corrected key
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false  # Corrected key
  month: false
  week: false
  24 hours: true  # Corrected key

positions:
  - Software Engineer
  - Data Analyst
  - Systems Engineer
  - Data Engineer
  - Data Scientist

locations:
  - New York
  - Brooklyn

apply_once_at_company: true

distance: 50

company_blacklist:
  - wayfair
  - blackjack

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil
